#!/usr/bin/env python3
"""Check client-visible business prose; never treat a successful scan as legal approval."""
import argparse
import json
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
POLICY = ROOT / "controls/document-engineering/client-facing-language.policy.json"

def violations(text):
    p = json.loads(POLICY.read_text(encoding="utf-8"))
    return [term for term in p["forbidden_visible_phrases"] if
            re.search(r"(?<![A-Za-z0-9])"+re.escape(term)+r"(?![A-Za-z0-9])", text, re.I)]

def check_pdf(path):
    if not shutil.which("pdftotext"):
        raise RuntimeError("pdftotext unavailable; cannot approve this PDF")
    body = subprocess.check_output(["pdftotext", "-layout", str(path), "-"], text=True)
    if not body.strip():
        raise ValueError("PDF has no extractable text; require visual check")
    errors = violations(body)
    if errors:
        raise ValueError("Client-facing PDF contains internal terminology: "+", ".join(errors))
    return len(body)

def selftest():
    assert not violations("Construction works agreement for uPVC windows and MS railings.")
    assert violations("Generated by ChatGPT and database")
    assert violations("The A9 control tower approved this document")
    assert not violations("Paid invoice; main gate; mountain view")
    print("PASS plain-language scanner fixture tests")

if __name__=="__main__":
    a=argparse.ArgumentParser()
    a.add_argument("--pdf",type=Path)
    a.add_argument("--text-file",type=Path)
    a.add_argument("--self-test",action="store_true")
    args=a.parse_args()
    if args.self_test:selftest()
    elif args.pdf:
        print("PASS visible PDF terminology, extracted characters:",check_pdf(args.pdf))
    elif args.text_file:
        v=violations(args.text_file.read_text(encoding="utf-8"))
        if v: raise SystemExit("Blocked forbidden wording: "+", ".join(v))
        print("PASS visible text terminology")
    else:a.error("Provide --pdf, --text-file or --self-test")
